version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/WoTTsecurity/ghostunnel
    steps:
      - checkout
      - run:
          name: Install depenedencies
          command: |
               sudo dpkg --add-architecture armel
               sudo dpkg --add-architecture armhf
               sudo dpkg --add-architecture i386
               sudo apt-get update
               sudo apt-get install libltdl-dev devscripts \
                crossbuild-essential-armel libltdl-dev:armel \
                crossbuild-essential-armhf libltdl-dev:armhf \
                binutils-multiarch libltdl-dev:i386 \
                ruby2.3-dev rubygems
      - run:
          name: Build amd64
          command: |
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=amd64 -aamd64 -i -us -uc -b
      - run:
          name: Build i386
          command: |
              sudo ln -s `which strip` /usr/bin/i686-linux-gnu-strip
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=386 -ai386 -i -us -uc -b
      - run:
          name: Build arm
          command: |
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=arm --set-envvar GOARM=6 -aarmel -i -us -uc -b
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=arm --set-envvar GOARM=6 -aarmhf -i -us -uc -b
      - run:
          name: Copy artifacts
          command: |
              mkdir -p /tmp/deb
              mv ../*.deb /tmp/deb
      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sudo gem install rake package_cloud
                for distro in debian/stretch raspbian/stretch debian/buster raspbian/buster ubuntu/xenial debian/jessie raspbian/jessie ubuntu/trusty; do
                  package_cloud push wott/agent/$distro /tmp/deb/*.deb
                done
              fi
      - store_artifacts:
          path: /tmp/deb
